### ISSUE TITLE
OAuth integration with Wikidata

### ISSUE THREAD

**Issue by carlwilson** [WikiDP/wikidp-portal#10]
Wikidata integrator seems to offer straightforward OAuth integration with Wikidata. Downside is that anyone with a Wikidata account has a working account on our system.

**Comment by carlwilson** [comment]
This needs a little thinking about from @kennethsn + @emulatingkat

**Comment by emulatingkat** [comment]
I checked in with the Scripps crew. They have not yet had a problem with the reality that anyone with Wikidata credentials being able to authorize the system to edit on their behalf.

**Comment by carlwilson** [comment]
And anyone with a Wikidata account can go ahead and just use Wikidata direct. This seems fine then, I'll look at implementing OAuth as a next task.

**Comment by emulatingkat** [comment]
WDI has been updated around OAuth. I think we will need to update to the newest version of the tool.

**Comment by emulatingkat** [comment]
I just asked for clarification (do we need the site up on our URL or is a placeholder ok). Link for discussion here: https://meta.wikimedia.org/wiki/Steward_requests/Miscellaneous#OAuth_approval_request_for_Wikidata_for_Digital_Preservation

**Comment by emulatingkat** [comment]
Here is the documentation about OAuth apps: https://meta.wikimedia.org/wiki/OAuth_app_guidelines

**Comment by emulatingkat** [comment]
Here is the info about the Wikibase docker image: https://addshore.com/2017/12/wikibase-docker-images/

**Comment by carlwilson** [comment]
This works now, so closing
