### ISSUE TITLE
search by mediatype not working

### ISSUE THREAD

**Issue by emulatingkat** [WikiDP/wikidp-portal#51]
I tried searching by mediatype but the portal did not return search results.

I don't think search by mediatype is working right now.

**Comment by kennethsn** [comment]
@emulatingkat  I know this issue is dated, but would be able to denote any media types that fail and I will look into them further to close this issue. (If you no longer experience this, then feel free to close it as well and reopen if you come across any down the road!)

**Comment by emulatingkat** [comment]
I tried: video/x-matroska

and it failed.
Thanks for checking this out!

**Comment by kennethsn** [comment]
Thank you for the example! 

Good news is that I just tried searching 'video/x-matroska' using the the code from PR #60 and the search was successful!

Once we merge PR #60 to master and update the production instance, this should take care of the issue.

**Comment by emulatingkat** [comment]
Awesome, thank you for letting me know.
